name: Build and Run Docker Server

on:
  workflow_dispatch:
    inputs:
      GIT_REPOSITORY_URL:
        description: 'User Git Repository URL'
        required: true
        type: string
      PROJECT_ID:
        description: 'Project ID'
        required: true
        type: string

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Docker Container
        env:
          GIT_REPOSITORY_URL: ${{ github.event.inputs.GIT_REPOSITORY_URL }}
          PROJECT_ID: ${{ github.event.inputs.PROJECT_ID }}
          VARIABLE_NAME: ${{ secrets.REDIS_URL }}
          ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          
          docker build -t build-server-image .

         
          docker run \
            -e GIT_REPOSITORY_URL="$GIT_REPOSITORY_URL" \
            -e PROJECT_ID="$PROJECT_ID" \
            -e VARIABLE_NAME="$VARIABLE_NAME" \
            -e ACCESS_ID="$ACCESS_ID" \
            -e SECRET_KEY="$SECRET_KEY" \
            build-server-image